// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_info.proto

package simple

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// UserInfo 的数据模型
type UserInfoModel struct {
	Userid               int64    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoModel) Reset()         { *m = UserInfoModel{} }
func (m *UserInfoModel) String() string { return proto.CompactTextString(m) }
func (*UserInfoModel) ProtoMessage()    {}
func (*UserInfoModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_info_14c9b25a4fce3585, []int{0}
}
func (m *UserInfoModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoModel.Unmarshal(m, b)
}
func (m *UserInfoModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoModel.Marshal(b, m, deterministic)
}
func (dst *UserInfoModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoModel.Merge(dst, src)
}
func (m *UserInfoModel) XXX_Size() int {
	return xxx_messageInfo_UserInfoModel.Size(m)
}
func (m *UserInfoModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoModel proto.InternalMessageInfo

func (m *UserInfoModel) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *UserInfoModel) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfoModel) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

// 请求结构
type UserInfoRequest struct {
	Userid               int64    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_info_14c9b25a4fce3585, []int{1}
}
func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(dst, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

// 响应结构
type UserInfoResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_info_14c9b25a4fce3585, []int{2}
}
func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (dst *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(dst, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfoModel)(nil), "simple.UserInfoModel")
	proto.RegisterType((*UserInfoRequest)(nil), "simple.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "simple.UserInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserInfoClient is the client API for UserInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInfoClient interface {
	// 定义 GetUserInfo 方法
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoModel, error)
	SetUserInfo(ctx context.Context, in *UserInfoModel, opts ...grpc.CallOption) (*UserInfoResponse, error)
}

type userInfoClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoClient(cc *grpc.ClientConn) UserInfoClient {
	return &userInfoClient{cc}
}

func (c *userInfoClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoModel, error) {
	out := new(UserInfoModel)
	err := c.cc.Invoke(ctx, "/simple.UserInfo/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoClient) SetUserInfo(ctx context.Context, in *UserInfoModel, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/simple.UserInfo/SetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInfoServer is the server API for UserInfo service.
type UserInfoServer interface {
	// 定义 GetUserInfo 方法
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfoModel, error)
	SetUserInfo(context.Context, *UserInfoModel) (*UserInfoResponse, error)
}

func RegisterUserInfoServer(s *grpc.Server, srv UserInfoServer) {
	s.RegisterService(&_UserInfo_serviceDesc, srv)
}

func _UserInfo_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.UserInfo/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInfo_SetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoServer).SetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.UserInfo/SetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoServer).SetUserInfo(ctx, req.(*UserInfoModel))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simple.UserInfo",
	HandlerType: (*UserInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserInfo_GetUserInfo_Handler,
		},
		{
			MethodName: "SetUserInfo",
			Handler:    _UserInfo_SetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_info.proto",
}

func init() { proto.RegisterFile("user_info.proto", fileDescriptor_user_info_14c9b25a4fce3585) }

var fileDescriptor_user_info_14c9b25a4fce3585 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xce, 0xcc,
	0x2d, 0xc8, 0x49, 0x55, 0x0a, 0xe5, 0xe2, 0x0d, 0x2d, 0x4e, 0x2d, 0xf2, 0xcc, 0x4b, 0xcb, 0xf7,
	0xcd, 0x4f, 0x49, 0xcd, 0x11, 0x12, 0xe3, 0x62, 0x03, 0xa9, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x40, 0xac, 0xbc, 0xc4, 0xdc, 0x54, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x80, 0x8b, 0x39, 0x31, 0x3d, 0x55, 0x82,
	0x59, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc4, 0x54, 0xd2, 0xe4, 0xe2, 0x87, 0x19, 0x1b, 0x94, 0x5a,
	0x58, 0x9a, 0x5a, 0x5c, 0x82, 0xcb, 0x60, 0x25, 0x0b, 0x2e, 0x01, 0x84, 0xd2, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xfc, 0x94, 0x54, 0xb0, 0x4a, 0xd6, 0x20, 0x30,
	0x1b, 0x64, 0x49, 0x6e, 0x71, 0x3a, 0xd4, 0x6e, 0x10, 0xd3, 0xa8, 0x97, 0x91, 0x8b, 0x03, 0xa6,
	0x55, 0xc8, 0x9e, 0x8b, 0xdb, 0x3d, 0xb5, 0x04, 0xce, 0x15, 0xd7, 0x83, 0x78, 0x50, 0x0f, 0xcd,
	0x19, 0x52, 0xa2, 0xe8, 0x12, 0x60, 0x6f, 0x2b, 0x31, 0x08, 0x39, 0x70, 0x71, 0x07, 0x23, 0x19,
	0x80, 0x5d, 0x9d, 0x94, 0x04, 0xa6, 0xb9, 0x10, 0x37, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0x83, 0xd6,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x40, 0xb0, 0x02, 0x6d, 0x01, 0x00, 0x00,
}
